In [1]:
from numpy import * #导入numpy库的函数
import numpy as np

In [2]:
#矩阵的创建
a1=array([1,2,3])
print(a1)

[1 2 3]


In [3]:
a1

array([1, 2, 3])

In [4]:
a1=mat(a1)
a1

matrix([[1, 2, 3]])

print(a1)

shape(a1)

b=matrix([1,2,3])
shape(b)

In [9]:
#创建常见矩阵
#(1)创建一个3*3的零矩阵
data1=mat(zeros((3,3)))
data1

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
#创建一个2*4的1矩阵，默认为浮点型
data2=mat(ones((2,4)))
data2

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
#这里的random模块使用的是numpy中的random模块，
#random.rand(2,2)创建的是一个二维数组，需要将其转换成#matrix
data3=mat(random.rand(2,2))
data3

matrix([[9.97842780e-01, 3.60501500e-01],
        [4.82033669e-01, 8.70568987e-04]])

In [19]:
#生成一个3*3的0-10之间的随机整数,如果需要指定下界则可以多加一个参数
data4=mat(random.randint(10,size=(3,3)))  
data4

matrix([[8, 1, 3],
        [8, 6, 1],
        [1, 3, 7]])

In [20]:
#产生一个2-8之间的随机整数矩阵
data5=mat(random.randint(2,8,size=(2,5)))
data5

matrix([[6, 5, 5, 5, 7],
        [2, 4, 3, 4, 7]])

In [23]:
#产生一个2*2的对角矩阵
data6=mat(eye(2,2,dtype=int))
data6

matrix([[1, 0],
        [0, 1]])

In [24]:
#生成一个对角线为1，2，3的对角矩阵
a1=[1,2,3]
a2=mat(diag(a1))
a2

matrix([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [25]:
#常见的矩阵运算
#矩阵相乘
a1=mat([1,2])
a2=mat([[1],[2]])  #1*2的矩阵乘以2*1的矩阵，得到1*1的矩阵
a3=a1*a2
a3

matrix([[5]])

In [27]:
#矩阵的点乘
a1=mat([3,1])
a2=mat([2,2])
a3=multiply(a1,a2)
a3

matrix([[6, 2]])

In [28]:
#矩阵求逆，转置
a1=mat(eye(2,2)*0.5)   #mat(eye(2,2))表示2*2的对角矩阵
a1

matrix([[0.5, 0. ],
        [0. , 0.5]])

In [30]:
a2=a1.I    #求矩阵matrix([[0.5, 0. ],[0. , 0.5]])的逆矩阵
a2

matrix([[2., 0.],
        [0., 2.]])

In [31]:
#矩阵的转置
a1=mat([[1,1],[0,0]])
a1

matrix([[1, 1],
        [0, 0]])

In [33]:
a2=a1.T
a2

matrix([[1, 0],
        [1, 0]])

In [34]:
#计算矩阵对应行列的最大值、最小值以及和
a1=mat([[1,1],[2,3],[4,2]])
a1

matrix([[1, 1],
        [2, 3],
        [4, 2]])

In [35]:
#计算每一列、行的和
a2=a1.sum(axis=0)   #列和，得到1*2的矩阵
a2

matrix([[7, 6]])

In [36]:
a3=a1.sum(axis=1)  #行和，得到3*1的矩阵
a3

matrix([[2],
        [5],
        [6]])

In [37]:
a4=sum(a1[1,:])  #计算第一行所有列的和，这里得到一个数值
a4    #第0行：1+1；第1行：2+3；第2行：4+2

5

In [43]:
#计算最大、最小值和索引 
a1.max()   #计算a1矩阵中所有元素的最大值，结果为一个数值
a2=max(a1[:,1])  #计算第二列的最大值，这里得到的是一个1*1的矩阵
#等价于
a2=(a1[:,1]).max() 

matrix([[3]])

In [45]:
(a1[1,:]).max()  #计算第二行的最大值，这里得到的是一个一个数值

3

In [51]:
np.max(a1,0)  #0表示矩阵的列,计算所有列的最大值，这里使用的是numpy中的max函数

matrix([[4, 3]])

In [52]:
np.max(a1,1)  #计算所有行的最大值，这里得到是一个矩阵

matrix([[1],
        [3],
        [4]])

In [53]:
np.argmax(a1,0)  #计算所有列的最大值对应在该列中的索引

matrix([[2, 1]], dtype=int64)

In [54]:
np.argmax(a1[1,:])  #计算第二行中最大值对应在该行中的索引

1

In [55]:
#矩阵的分隔和合并
#矩阵的分隔用列表、数组的分隔一致
a=mat(ones((3,3)))
a

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [56]:
b=a[1:,1:]  #分割出第二行以后的行和第二列以后的列的所有元素
b

matrix([[1., 1.],
        [1., 1.]])

In [57]:
#矩阵的合并
a=mat(ones((2,2)))
a

matrix([[1., 1.],
        [1., 1.]])

In [58]:
b=mat(eye(2))
b

matrix([[1., 0.],
        [0., 1.]])

In [60]:
#矩阵的拼接/切分
#np.vstack()  竖着拼接，np.hstack()横着拼接
#np.vsplit()  竖着切分，
c=vstack((a,b))   #按列合并，即增加行数
c

matrix([[1., 1.],
        [1., 1.],
        [1., 0.],
        [0., 1.]])

In [61]:
d=hstack((a,b))   #按行合并，即行数不变，扩展列数
d

matrix([[1., 1., 1., 0.],
        [1., 1., 0., 1.]])

In [131]:
#ndarray的拼接/切分
#np.vstack()  竖着拼接，np.hstack()横着拼接
#np.vsplit()  竖着切分，
n1=np.array([[10,11],
             [12,13]])
n2=np.array([[20,21],
             [22,23]])
hstack=np.hstack((n1,n2))   #横向拼接
print(hstack)
vstack=np.vstack((n1,n2))  #竖向拼接
print(vstack)
#np.hsplit()  #横向切分
n3=np.floor(10*np.random.random((2,12)))
print(n3)
print(np.hsplit(n3,3))
print(np.hsplit(n3,(3,5)))  #指定切分位置
#np.vsplit()   #竖着切
n4=n3.T
print(n4)

[[10 11 20 21]
 [12 13 22 23]]
[[10 11]
 [12 13]
 [20 21]
 [22 23]]
[[1. 7. 0. 3. 0. 7. 6. 0. 2. 0. 6. 5.]
 [3. 0. 9. 1. 7. 3. 7. 4. 8. 0. 4. 5.]]
[array([[1., 7., 0., 3.],
       [3., 0., 9., 1.]]), array([[0., 7., 6., 0.],
       [7., 3., 7., 4.]]), array([[2., 0., 6., 5.],
       [8., 0., 4., 5.]])]
[array([[1., 7., 0.],
       [3., 0., 9.]]), array([[3., 0.],
       [1., 7.]]), array([[7., 6., 0., 2., 0., 6., 5.],
       [3., 7., 4., 8., 0., 4., 5.]])]


In [133]:
n4=n3.T
print(n4)
print(np.vsplit(n4,3))

[[1. 3.]
 [7. 0.]
 [0. 9.]
 [3. 1.]
 [0. 7.]
 [7. 3.]
 [6. 7.]
 [0. 4.]
 [2. 8.]
 [0. 0.]
 [6. 4.]
 [5. 5.]]
[array([[1., 3.],
       [7., 0.],
       [0., 9.],
       [3., 1.]]), array([[0., 7.],
       [7., 3.],
       [6., 7.],
       [0., 4.]]), array([[2., 8.],
       [0., 0.],
       [6., 4.],
       [5., 5.]])]


In [63]:
#矩阵、列表、数组的转换
#列表可以修改，且列表中元素可以使用不同类型的数据
list1=[[1],'hello',3]
list1

[[1], 'hello', 3]

In [64]:
#然而，numpy中数组，同一个数组中所有元素必须为同一个类型，有几个常见的属性：
a=array([[2],[1]])
a

array([[2],
       [1]])

In [66]:
diemnsion=a.ndim   #
diemnsion

2

In [67]:
m,n=a.shape   #m,n分别表示行、列数

In [68]:
m

2

In [69]:
n

1

In [71]:
number=a.size   #元素的总个数
number

2

In [72]:
str=a.dtype   #元素的类型
str

dtype('int32')

In [73]:
# numpy中的矩阵也有与数组常见的几个属性。 
# 它们之间的转换：
a1=[[1,2],[3,2],[5,2]]   #列表
a1

[[1, 2], [3, 2], [5, 2]]

In [74]:
a2=array(a1)   #按列表转换成二维数组
a2

array([[1, 2],
       [3, 2],
       [5, 2]])

In [75]:
a3=mat(a1)  #将列表转化成矩阵
a3

matrix([[1, 2],
        [3, 2],
        [5, 2]])

In [76]:
a4=array(a3)   #将矩阵转换为数组
a4

array([[1, 2],
       [3, 2],
       [5, 2]])

In [77]:
a41=a3.getA()   ##将矩阵转换成数组
a41

array([[1, 2],
       [3, 2],
       [5, 2]])

In [78]:
a5=a3.tolist()   #将矩阵转换为列表
a5

[[1, 2], [3, 2], [5, 2]]

In [81]:
a6=a2.tolist()   ##将数组转换成列表
a6

[[1, 2], [3, 2], [5, 2]]

In [82]:
#这里可以发现三者之间的转换是非常简单的，这里需要注意的是，当列表是一维的时候，将它转换成数组和矩阵后，再通过tolist()转换成列表是不相同的，需要做一些小小的修改。如下：
a1=[1,2,3]
a2=array(a1)
a2

array([1, 2, 3])

In [83]:
a3=mat(a1)
a3

matrix([[1, 2, 3]])

In [84]:
a4=a2.tolist()
a4

[1, 2, 3]

In [87]:
a5=a3.tolist()
a5

[[1, 2, 3]]

In [88]:
a6=(a4==a5)
a6

False

In [96]:
a7=(a4 == a5[0])
a7

True

In [93]:
a5[0]

[1, 2, 3]

In [99]:
#矩阵转换成数值，存在以下一种情况：
dataMat=mat([1])
val=dataMat[0,0] #这个时候获取的就是矩阵的元素的数值，而不再是矩阵的类型
val

1

In [100]:
#numpy的常见数学运算
import numpy as np
n=np.array([[5,10,15],
            [20,25,30],
            [35,40,45]])

In [103]:
print(n.min())   #数组n的最小值5
print(n.max())   #数组n的最大值45
print(n.mean())  #数组n的均值25
print(n.sum())   #数组n所有元素的和225

5
45
25.0
225


In [104]:
#指定所操作额维度，axis=0，表示列，axis=1,表示行
print(n.sum(axis=0))
print(n.sum(axis=1))

[60 75 90]
[ 30  75 120]


In [109]:
n1=np.arange(3)
print(n1)
print(np.exp(n1))
print(np.sqrt(n1))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [110]:
n2=np.random.random((2,3))*10
#np.floor 返回不大于输入参数的最大整数。 
# 即对于输入值 x ，将返回最大的整数 i ，使得 i <= x。 注意在Python中，向下取整总是从 0 舍入。
n3=np.floor(n2)  
print(n2)
print(n3)

[[0.55567079 0.0794295  0.02150215]
 [9.15899787 8.53893765 4.42095859]]
[[0. 0. 0.]
 [9. 8. 4.]]


In [111]:
#np.sort()排序
a=np.array([[4,3,5],[1,6,1]])
print(a)

[[4 3 5]
 [1 6 1]]


In [116]:
#按行大小排序
b=np.sort(a,axis=1)   #指定所操作的维度，axis=0，表示列，axis=1,表示行
print(b)
#或者
a.sort(axis=1)  #直接对数组a进行排序

[[3 4 5]
 [1 1 6]]


In [117]:
#np.argsort()  #排序的索引
a2=np.array([4,3,1,2])
j=np.argsort(a2)   #j将原数组a2中各元素的索引按元素值的大小排序后，索引的顺序，如4的索引为0，3的索引为1，依次类推
print(j)
print(a2[j])

[2 3 1 0]
[1 2 3 4]


In [126]:
#矩阵元素相乘
#将对应位置的元素相乘
#使用*来连接两个np矩阵，如n1*n2
#或者np.multiply(n1,n2) ，
# 1. 当为array的时候，默认d*f就是对应元素的乘积，multiply也是对应元素的乘积，dot（d,f）会转化为矩阵的乘积， dot点乘意味着相加，而multiply只是对应元素相乘，不相加
# 2. 当为mat的时候，默认d*f就是矩阵的乘积，multiply转化为对应元素的乘积，dot（d,f）为矩阵的乘积
n1=np.array([[1,1],
             [0,1]])
n2=np.array([[2,0],
             [3,4]])
print(n1)
print(n2)
print(n1*n2)        #仅为两数组的对对应项元素的乘积
print(multiply(n1,n2))  #与用*连接等价，仅为两数组的对应项元素的乘积
print(np.multiply(n1,3))   #数组n1的各对应元素均乘以3
print(dot(n1,n2))    #矩阵的乘法，同线性代数中矩阵乘法
print(matmul(n1,n2))  #np.matmul(a,b,out=None)与np.dot功能一样。

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[2 0]
 [0 4]]
[[3 3]
 [0 3]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [ ]:
#